DATASETS:
  NAMES: ('VOC')
  SUBSET: ('train')
  ROOT_DIR: ('../../datasets/VOC')
  SCALE: (1024, 1024)

MODEL:
  BACKBONE: 'resnet101'
  WEIGHTS: 'COCO'
  INPUT_SHAPE: (1024, 1024)
  ANCHOR_SCALES: (64, 128, 256, 512)
  ANCHOR_FEATURE_STRIDES: (16, 16, 16, 16)
  
SOLVER:
  WARMUP_STEPS: 1000
  TOTAL_STEPS: 20000

