DATASETS:
  NAMES: ('COCO')
  SUBSET: ('val')
  ROOT_DIR: ('./datasets/COCO2017')
  IMAGE_DIR: ('./datasets/test/')
  SCALE: (1024, 1024)

MODEL:
  BACKBONE: 'resnet101'
  WEIGHTS: ('training/faster_rcnn_68000.h5')
  ANCHOR_SCALES: (64, 128, 256, 512)
  ANCHOR_FEATURE_STRIDES: (16, 16, 16, 16)
  RPN_PROPOSAL_NMS_TOP_N: 6000
  RPN_PROPOSAL_COUNT: 300
